import Header from '@/components/Header/Header'
import { signIn } from '@/libs/auth/oAuth'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const googleSignIn = async () => {
    'use server'
    await signIn('google')
  }
  const gitHubSignIn = async () => {
    'use server'
    await signIn('github')
  }

  const signInAction = async (formData: FormData) => {
    'use server'
    await signIn('credentials', formData)
  }

  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header
          gitHubSignIn={gitHubSignIn}
          googleSignIn={googleSignIn}
          signInAction={signInAction}
        />
        {children}
      </body>
    </html>
  )
}
