import Header from '@/components/Header/Header'
import { TUserInfoProps } from '@/components/UserInfo/UserInfo'
import { gitHubSignIn, googleSignIn } from '@/libs/actions/auth'
import { signIn, signOut } from '@/libs/auth/credential'
import { getCurrentSession } from '@/libs/auth/session'

import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getCurrentSession()
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header
          currentUser={session as TUserInfoProps}
          signInAction={signIn}
          gitHubSignIn={gitHubSignIn}
          googleSignIn={googleSignIn}
          signOut={signOut}
        />
        {children}
      </body>
    </html>
  )
}
