import Header from '@/components/Header/Header'
import { gitHubSignIn, googleSignIn, signInAction } from '@/libs/actions/auth'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header
          signInAction={signInAction}
          gitHubSignIn={gitHubSignIn}
          googleSignIn={googleSignIn}
        />
        {children}
      </body>
    </html>
  )
}
